/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Desenvolvedor;

import Controle.ControladoraIdioma;
import Modelo.Acao;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class JanelaDesenvolvimentoAcao extends javax.swing.JFrame {

    private final JanelaDesenvolvimentoSaida janelaDevSaida;
    private final ControladoraIdioma idioma;
    private final Acao acao;

    /**
     * Creates new form JanelaDesenvolvimentoAcao
     *
     * @param janelaDevSaida
     * @param acao
     */
    public JanelaDesenvolvimentoAcao(JanelaDesenvolvimentoSaida janelaDevSaida, Acao acao) {

        initComponents();
        setLocationRelativeTo(janelaDevSaida);

        idioma = ControladoraIdioma.getInstancia();
        this.acao = acao;
        this.janelaDevSaida = janelaDevSaida;

        CarregarAcao();
        PreencheComboOperacoes();
    }

    public final void CarregarAcao() {
        txtNomeVariavel.setText(acao.getVariavel().getNome());
        jspValor.setToolTipText("Teste");
        jspValor.setValue(acao.getNumero());
    }

    public final void PreencheComboOperacoes() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        model.addElement(idioma.Valor("lblNennhuma"));
        model.addElement(idioma.Valor("lblSomar"));
        model.addElement(idioma.Valor("lblSubtrair"));
        model.addElement(idioma.Valor("lblMultiplicar"));
        model.addElement(idioma.Valor("lblDividir"));

        cbxOperacao.setModel(model);

        cbxOperacao.setSelectedIndex(acao.getOperacao());
    }

    public void SalvarAcao() {

        boolean ok = ValidarDados();

        if (ok) {
            acao.setNumero((double) jspValor.getValue());

            int operacao = cbxOperacao.getSelectedIndex();
            System.out.println("operacao " + operacao);

            acao.setOperacao(operacao);

            janelaDevSaida.AtualizarAcoes();

            dispose();
        }

    }
    
    /**
     * 
     * @return 
     */
    public boolean ValidarDados()
    {
        boolean ok = true;
        ArrayList<String> mensagens = new ArrayList<>();
        String mensagem;
        
        double valor = (double)jspValor.getValue();
        String operacao = (String)cbxOperacao.getSelectedItem();
        if(cbxOperacao.getSelectedItem().equals(idioma.Valor("lblDividir")) && valor == 0)
        {
            ok = false;
            mensagem = idioma.Valor("msgDivisaoZero");
            mensagens.add(mensagem);
        }
        
        if(!ok)
        {
            String mensagemJanela = "";

            for (String s : mensagens) {
                mensagemJanela += s + "\n";
            }

            JOptionPane.showMessageDialog(this, mensagemJanela, idioma.Valor("lblAviso"), JOptionPane.OK_OPTION);
        }
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAcao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jspValor = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        txtNomeVariavel = new javax.swing.JTextField();
        cbxOperacao = new javax.swing.JComboBox();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("lblVariavel");

        lblAcao.setText("lblAcao");

        jLabel3.setText("lblValor");

        jspValor.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        jspValor.setToolTipText("");

        jButton1.setText("bntAjuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setText("btnCancelar");

        btnConfirmar.setText("btnConfirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        txtNomeVariavel.setEditable(false);

        cbxOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lblAcao)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspValor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeVariavel)
                    .addComponent(cbxOperacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcao)
                    .addComponent(cbxOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jspValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        SalvarAcao();

    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox cbxOperacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jspValor;
    private javax.swing.JLabel lblAcao;
    private javax.swing.JTextField txtNomeVariavel;
    // End of variables declaration//GEN-END:variables
}
