/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Desenvolvedor;

import Controle.ControladoraAjuda;
import Controle.ControladoraIdioma;
import GUI.Suporte.LimiteCaracteres;
import Modelo.Acao;
import Modelo.Partida;
import Modelo.SaidaNumerica;
import Modelo.SaidaOpcional;
import Modelo.Situacao;
import Modelo.Variavel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class JanelaDesenvolvimentoVariavel extends javax.swing.JFrame {

    private final Partida partidaDesenvolvimento;

    private final JanelaDesenvolvimentoPartida janelaDesenvolvimento;
    private final int modo;
    private final Variavel variavel;
    private final ControladoraIdioma idioma;

    /**
     * Creates new form JanelaDesenvolvimentoVariavel
     *
     * @param modo
     * @param variavel
     */
    public JanelaDesenvolvimentoVariavel(int modo, Variavel variavel) {
        initComponents();

        partidaDesenvolvimento = Partida.getInstancia();

        janelaDesenvolvimento = JanelaDesenvolvimentoPartida.getInstancia();

        idioma = ControladoraIdioma.getInstancia();

        CarregaIdioma();

        setLocationRelativeTo(janelaDesenvolvimento);

        this.variavel = variavel;
        this.modo = modo;

        //Limita o nome da variável em 30
        txtNomeVariavel.setDocument(new LimiteCaracteres(20));
        
        //Caso o modo seja edição, preenche os campos
        if (modo == 2) {
            CarregarVariavel();
        }
    }

    public final void CarregaIdioma() {
        chbOculta.setText(idioma.Valor("lblOculta"));
        lblNome.setText(idioma.Valor("lblNomeVariavel"));
        lblValorInicial.setText(idioma.Valor("lblValorInicial"));
        btnAjuda.setText(idioma.Valor("btnAjuda"));
        btnCancelar.setText(idioma.Valor("btnCancelar"));
        btnConfirmar.setText(idioma.Valor("btnConfirmar"));
        lblTitulo.setText(idioma.Valor("tituloDesenvVariavel"));
        
        setTitle(idioma.Valor("tituloDesenvVariavel"));
    }

    public final void CarregarVariavel() {
        txtNomeVariavel.setText(variavel.getNome());
        jspValorInicial.setValue(variavel.getValorInicial());
        chbOculta.setSelected(variavel.isOculta());
    }

    public void SalvarVariavel() {
        boolean ok = ValidarDados();

        if (ok) {
            variavel.setNome(txtNomeVariavel.getText());
            variavel.setValorInicial((double) jspValorInicial.getValue());
            variavel.setOculta(chbOculta.isSelected());

            //Caso o modo seja inserir, adiciona a variável à partida
            if (modo == 1) {
                partidaDesenvolvimento.getVariaveis().add(variavel);
                CriarAcoesVariavel();
            }
            
            janelaDesenvolvimento.AtualizarDados();
            dispose();
        }
    }

    /**
     * Validação dos dados
     *
     * @return
     */
    public boolean ValidarDados() {
        boolean ok = true;
        if (txtNomeVariavel.getText().isEmpty()) {
            ok = false;
            JOptionPane.showMessageDialog(this, idioma.Valor("msgNomeVariavelObrigatorio"), idioma.Valor("aviso"), JOptionPane.OK_OPTION);
        }
        return ok;
    }

    /**
     * Pré-cria as ações para a variável em cada saída
     */
    public void CriarAcoesVariavel() {
        for (Situacao situacao : partidaDesenvolvimento.getSituacoes()) {
            if (situacao.getSaida().getTipoSaida() == 1) {

                ArrayList<SaidaOpcional> saidasO = situacao.getSaida().getSaidasOpcao();

                for (SaidaOpcional saida : saidasO) {
                    Acao acao = new Acao();
                    acao.setVariavel(variavel);
                    acao.setNumero(0);
                    acao.setOperacao(0);
                    acao.setOculta(false);

                    saida.getAcoes().add(acao);
                }

            } else {

                ArrayList<SaidaNumerica> saidasN = situacao.getSaida().getSaidasNumerica();

                for (SaidaNumerica saida : saidasN) {
                    Acao acao = new Acao();
                    acao.setVariavel(variavel);
                    acao.setNumero(0);
                    acao.setOperacao(0);

                    saida.getAcoes().add(acao);
                }

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblValorInicial = new javax.swing.JLabel();
        chbOculta = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        txtNomeVariavel = new javax.swing.JTextField();
        btnAjuda = new javax.swing.JButton();
        jspValorInicial = new javax.swing.JSpinner();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblNome.setText("lblNome");

        lblValorInicial.setText("lblValorInicial");

        chbOculta.setText("lblOculta");

        btnCancelar.setText("btnCancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("btnConfirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjuda.setText("btnAjuda");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });

        jspValorInicial.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("lblTitulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjuda))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorInicial)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeVariavel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chbOculta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jspValorInicial))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnAjuda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorInicial)
                    .addComponent(jspValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbOculta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        SalvarVariavel();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        ControladoraAjuda caj = new ControladoraAjuda();
        caj.ExibirAjuda(this, "DesenvolvimentoVariavel");
    }//GEN-LAST:event_btnAjudaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chbOculta;
    private javax.swing.JSpinner jspValorInicial;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorInicial;
    private javax.swing.JTextField txtNomeVariavel;
    // End of variables declaration//GEN-END:variables
}
