/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Desenvolvedor;

import Modelo.AcaoSaidaNumerica;
import Modelo.Partida;
import Modelo.Situacao;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Rafael
 */
public class JanelaDesenvolvimentoSaidaNumerica extends javax.swing.JFrame {

    //1. Inserir, 2. Editar
    int acao;

    JanelaDesenvolvimentoSaida jnlDevSaida;

    AcaoSaidaNumerica acaoSaidaNumerica;

    Partida partidaDesenvolvimento;

    Situacao situacaoDestino;

    /**
     * Creates new form JanelaDesenvolvimentoSaidaNumerica
     *
     * @param jds
     * @param acao
     * @param asn
     */
    public JanelaDesenvolvimentoSaidaNumerica(JanelaDesenvolvimentoSaida jds, int acao, AcaoSaidaNumerica asn) {
        initComponents();
        setLocationRelativeTo(jds);

        partidaDesenvolvimento = Partida.getInstancia();

        this.acao = acao;

        jnlDevSaida = jds;

        if (acao == 1) {
            acaoSaidaNumerica = new AcaoSaidaNumerica();
            situacaoDestino = new Situacao();
        } else {
            acaoSaidaNumerica = asn;
            CarregarAcaoSN();
        }

        CarregarSituacoes();

    }

    /**
     * Carregar os recursos de acordo com o idioma selecionado
     */
    public void CarregarRecursos() {

    }

    /**
     * Carregar as informações da ação da sáida numérica
     */
    public final void CarregarAcaoSN() {
        //Caso a ação seja default, bloqueia alguns campos
        if (acaoSaidaNumerica.isAcaoSNDefault()) {
            BloqueiaCamposAcaoDefaultSN();
        } else {
            spnValMaximo.setValue(acaoSaidaNumerica.getFaixa().getLimiteSuperior());
            spnValMinimo.setValue(acaoSaidaNumerica.getFaixa().getLimiteInferior());
        }

        txtDescricao.setText(acaoSaidaNumerica.getDescricao());
        txaFalaAssistente.setText(acaoSaidaNumerica.getFalaAssistente());

        situacaoDestino = acaoSaidaNumerica.getSituacaoDestino();
    }

    /**
     * Bloquear campos p/ ação default
     */
    public void BloqueiaCamposAcaoDefaultSN() {
        txtDescricao.setEnabled(false);
        spnValMinimo.setEnabled(false);
        spnValMaximo.setEnabled(false);
    }

    public final void CarregarSituacoes() {
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        int index = 0;
        int indexItemSelecionado = 0;
        
        for (Situacao s : partidaDesenvolvimento.getSituacoes()) {
            model.addElement(s.getNome());
            if (s == situacaoDestino) {
                indexItemSelecionado = index;
            }
            index++;
        }
        
        cbxSituacoes.setModel(model);
        cbxSituacoes.setSelectedIndex(indexItemSelecionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxSituacoes = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaFalaAssistente = new javax.swing.JTextArea();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        spnValMinimo = new javax.swing.JSpinner();
        spnValMaximo = new javax.swing.JSpinner();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("lblValorMinimo");

        jLabel2.setText("lblValorMaximo");

        jLabel3.setText("lblSituacaoDestino");

        cbxSituacoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSituacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSituacoesActionPerformed(evt);
            }
        });

        jLabel4.setText("lblFalaAssistente");

        txaFalaAssistente.setColumns(20);
        txaFalaAssistente.setRows(5);
        jScrollPane1.setViewportView(txaFalaAssistente);

        btnConfirmar.setText("btnConfirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("btnCancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        spnValMinimo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spnValMaximo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        lblDescricao.setText("lblDescricao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescricao)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnValMinimo)
                            .addComponent(spnValMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSituacoes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnValMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnValMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxSituacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        acaoSaidaNumerica.setDescricao(txtDescricao.getText());
        acaoSaidaNumerica.setFalaAssistente(txaFalaAssistente.getText());
        acaoSaidaNumerica.setSituacaoDestino(situacaoDestino);

        jnlDevSaida.AtualizaTabelaAcoesDefaultSN();
        dispose();

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxSituacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSituacoesActionPerformed

        int index = cbxSituacoes.getSelectedIndex();

        situacaoDestino = partidaDesenvolvimento.getSituacoes().get(index);


    }//GEN-LAST:event_cbxSituacoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox cbxSituacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JSpinner spnValMaximo;
    private javax.swing.JSpinner spnValMinimo;
    private javax.swing.JTextArea txaFalaAssistente;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
