/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Desenvolvedor;

import Controle.ControladoraIdioma;
import Modelo.Partida;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Bruno
 */
public class JanelaSelecionaAvatar extends javax.swing.JDialog {

    private ArrayList<ImageIcon> avatares;
    private final ControladoraIdioma idioma;
    private JanelaDesenvolvimentoPartida jdp;
    private final Partida partidaDesenvolvimento;
    private ImageIcon avatarSelecionado;

    /**
     * Creates new form JanelaSelecionaAvatar
     */
    public JanelaSelecionaAvatar() {
        initComponents();
        setModal(true);

        idioma = ControladoraIdioma.getInstancia();
        partidaDesenvolvimento = Partida.getInstancia();
        jdp = JanelaDesenvolvimentoPartida.getInstancia();

        setLocationRelativeTo(jdp);
        CarregaIdioma();
        CarregaAvatares();

    }

    public final void CarregaIdioma() {
        btnCancelar.setText(idioma.Valor("btnCancelar"));
        btnConfirmar.setText(idioma.Valor("btnConfirmar"));
        lblPersonagemAvaliacoes.setText(idioma.Valor("lblPersonagemAvaliacoes"));
        setTitle(idioma.Valor("bordaSelecioneAvatar"));
    }

    /**
     * Carrega os avatares do assistente
     */
    public final void CarregaAvatares() {

        int itemSelecionado = 0;
        imgAvatar.setText(idioma.Valor("lblSelecioneUmAvatar"));
        DefaultListModel itens = new DefaultListModel<>();
        avatares = new ArrayList<>();

        //Recupera a quantidade de avatares disponiveis
        File file = new File("Arquivos/Avatares");
        File arquivos[] = file.listFiles();

        for (int i = 0; i < arquivos.length; i++) {

            ImageIcon avatar = new ImageIcon(arquivos[i].getAbsolutePath());
            avatar.setDescription(arquivos[i].getName());
            avatares.add(avatar);
            if (partidaDesenvolvimento.getAvatarDasAvaliacoes() != null) {
                if (partidaDesenvolvimento.getAvatarDasAvaliacoes().getDescription().equals(avatar.getDescription())) {
                    itemSelecionado = i;
                }
            }
            itens.addElement(arquivos[i].getName());
        }
        lstAvatares.setModel(itens);
        lstAvatares.setSelectedIndex(itemSelecionado);
    }

    public void SelecionarAvatar() {
        int index = lstAvatares.getSelectedIndex();
        if (index > -1) {
            avatarSelecionado = avatares.get(index);
            imgAvatar.setText(null);
            ImageIcon icone = new ImageIcon();
            icone.setImage(avatarSelecionado.getImage().getScaledInstance(120, 120, 120));
            imgAvatar.setIcon(icone);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAssistenteP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAvatares = new javax.swing.JList();
        imgAvatar = new javax.swing.JLabel();
        lblPersonagemAvaliacoes = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstAvatares.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstAvatares.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAvataresValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstAvatares);

        imgAvatar.setText("imgAvatar");

        lblPersonagemAvaliacoes.setText("lblPersonagemAvaliacoes");

        javax.swing.GroupLayout pnlAssistentePLayout = new javax.swing.GroupLayout(pnlAssistenteP);
        pnlAssistenteP.setLayout(pnlAssistentePLayout);
        pnlAssistentePLayout.setHorizontalGroup(
            pnlAssistentePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssistentePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAssistentePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAssistentePLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPersonagemAvaliacoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAssistentePLayout.setVerticalGroup(
            pnlAssistentePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssistentePLayout.createSequentialGroup()
                .addComponent(lblPersonagemAvaliacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAssistentePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmar.setText("btnConfirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("btnCancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAssistenteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAssistenteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstAvataresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAvataresValueChanged
        SelecionarAvatar();
    }//GEN-LAST:event_lstAvataresValueChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        partidaDesenvolvimento.setAvatarDasAvaliacoes(avatarSelecionado);
        jdp.AtualizaAvaliacoes();
        dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel imgAvatar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPersonagemAvaliacoes;
    private javax.swing.JList lstAvatares;
    private javax.swing.JPanel pnlAssistenteP;
    // End of variables declaration//GEN-END:variables
}
