/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Desenvolvedor;

import Controle.ControladoraIdioma;
import Modelo.Avaliacao;
import Modelo.Partida;
import Modelo.Variavel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class JanelaDesenvolvimentoAvaliacao extends javax.swing.JFrame {

    private final JanelaDesenvolvimentoPartida janelaDevPartida;
    private final Avaliacao avaliacao;
    private final Partida partidaDesenvolvimento;
    private final int modo;
    private Variavel variavel;
    private final ControladoraIdioma idioma;

    /**
     * Creates new form JanelaDesenvolvimentoAvaliacao
     *
     * @param modo
     * @param avaliacao
     */
    public JanelaDesenvolvimentoAvaliacao(int modo, Avaliacao avaliacao) {
        initComponents();

        janelaDevPartida = JanelaDesenvolvimentoPartida.getInstancia();
        partidaDesenvolvimento = Partida.getInstancia();
        idioma = ControladoraIdioma.getInstancia();

        setLocationRelativeTo(janelaDevPartida);

        this.avaliacao = avaliacao;
        this.modo = modo;

        if (modo == 2) {
            CarregarAvaliacao();
        }
        CarregarVariaveis();

    }

    /**
     * Carrega os dados da avaliação
     */
    public final void CarregarAvaliacao() {
        txtDescricao.setText(avaliacao.getDescricao());
        jspValorInicial.setValue(avaliacao.getValorInicial());
        jspValorFinal.setValue(avaliacao.getValorFinal());
        txaTextoAvaliacao.setText(avaliacao.getTexto());
    }

    /**
     * Carrega o combo de variáveis
     */
    public final void CarregarVariaveis() {
        int index = 0;
        int itemSelecionado = 0;

        DefaultComboBoxModel model = new DefaultComboBoxModel();

        for (Variavel v : partidaDesenvolvimento.getVariaveis()) {
            model.addElement(v.getNome());

            if (v == avaliacao.getVariavel()) {
                itemSelecionado = index;
            }
            index++;
        }

        cbxVariavel.setModel(model);
        cbxVariavel.setSelectedIndex(itemSelecionado);
        variavel = partidaDesenvolvimento.getVariaveis().get(itemSelecionado);
    }

    public void SalvarAvaliacao() {
        
        boolean ok = ValidarDados();

        if (ok) {
            avaliacao.setDescricao(txtDescricao.getText());
            avaliacao.setValorInicial((double) jspValorInicial.getValue());
            avaliacao.setValorFinal((double) jspValorFinal.getValue());
            avaliacao.setVariavel(variavel);
            avaliacao.setTexto(txaTextoAvaliacao.getText());

            if (modo == 1) {
                partidaDesenvolvimento.getAvaliacoes().add(avaliacao);
            }

            janelaDevPartida.AtualizarDados();
            dispose();
        }

    }
    
    /**
     * Validação dos dados
     */
    public boolean ValidarDados()
    {
        boolean ok = true;
        ArrayList<String> mensagens = new ArrayList<>();
        String mensagem;
        
        if(txtDescricao.getText().isEmpty())
        {
            ok = false;
            mensagem = idioma.Valor("msgDescricaoObrigatoria");
            mensagens.add(mensagem);
            
        }
        if(txaTextoAvaliacao.getText().isEmpty())
        {
            ok = false;
            mensagem = idioma.Valor("msgTextoObrigatorio");
            mensagens.add(mensagem);
            
        }
        
        double valorInicial = (double)jspValorInicial.getValue();
        double valorFinal = (double)jspValorFinal.getValue();
        
        if(valorInicial >= valorFinal)
        {
            ok = false;
            mensagem = idioma.Valor("msgValorInicialMenor");
            mensagens.add(mensagem);
        }
        
        //Exibe as mensagens
        if(!ok)
        {
            String mensagemJanela = "";

            for (String s : mensagens) {
                mensagemJanela += s + "\n";
            }

            JOptionPane.showMessageDialog(this, mensagemJanela, idioma.Valor("lblAviso"), JOptionPane.OK_OPTION);
        }
        
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        cbxVariavel = new javax.swing.JComboBox();
        jspValorInicial = new javax.swing.JSpinner();
        jspValorFinal = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTextoAvaliacao = new javax.swing.JTextArea();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("lblDescricao");

        jLabel2.setText("lblVariavel");

        jLabel3.setText("lblValorInicial");

        jLabel4.setText("lvlValorFinal");

        jLabel5.setText("lblTextoAvaliacao");

        cbxVariavel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVariavelActionPerformed(evt);
            }
        });

        jspValorInicial.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        jspValorFinal.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        txaTextoAvaliacao.setColumns(20);
        txaTextoAvaliacao.setRows(5);
        jScrollPane1.setViewportView(txaTextoAvaliacao);

        btnConfirmar.setText("btnConfirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("btnCancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescricao)
                        .addComponent(cbxVariavel, 0, 282, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jspValorFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(jspValorInicial, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jspValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jspValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        SalvarAvaliacao();

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVariavelActionPerformed

        int index = cbxVariavel.getSelectedIndex();

        variavel = partidaDesenvolvimento.getVariaveis().get(index);

    }//GEN-LAST:event_cbxVariavelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox cbxVariavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jspValorFinal;
    private javax.swing.JSpinner jspValorInicial;
    private javax.swing.JTextArea txaTextoAvaliacao;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
