/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Jogador;

import Modelo.Situacao;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Rafael
 */
public class JanelaSituacaoJogo extends javax.swing.JFrame {

    ImageIcon imagemFundo;
    
    public JanelaSituacaoJogo(Situacao situacao) {
        initComponents();
        //setLocationRelativeTo(null);
        
        //URL url = getClass().getResource("./teste.jpg");
        
        //imagemFundo = situacao.getFundoSituacao();
        imagemFundo = situacao.getFundoSituacao();
        
        
        
        jLabel1.setIcon(imagemFundo);
        jLabel1.setText(null);
//        Graphics g = null;
//        
//        imagem = Toolkit.getDefaultToolkit().createImage("C:/Teste.jpg");
//        
//        super.paintComponents(g);
//        g.drawImage(imagem, 0, 0, this);
        
        
        //Icon icone;
        //jLabel1.setIcon(icone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 990, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 754, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
