/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Jogador;

import Modelo.Assistente;
import Modelo.Saida;
import Modelo.Situacao;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Rafael
 */
public final class JanelaSituacaoJogo extends javax.swing.JFrame {

    private final JPanel imgFundo;
    private final JPanel imgAvatar;
    private final JPanel imgBalao;

    private final ImageIcon imagemAvatar;
    private final ImageIcon imagemBalao;

    private final JTextArea textoBalao;

    private final JPanel painelBotoes;

    private final ArrayList<JButton> botoesSaidas;

    private JButton btn;

    public JanelaSituacaoJogo(Situacao situacao, Assistente assistente) {
        initComponents();

        botoesSaidas = new ArrayList<>();

        setLocationRelativeTo(null);
        setResizable(false);

        //Obtem o avatar do assistente
        imagemAvatar = new ImageIcon("./Recursos/" + assistente.getAvatarAssistente() + ".gif");

        //Obtem a imagem do balão
        imagemBalao = new ImageIcon("./Recursos/balao.gif");

        //Ajusta o tamanho da tela
        painelPrincipal.setSize(1024, 768);

        //Desenha a imagem de fundo
        imgFundo = new PainelImagem(situacao.getFundoSituacao());
        imgFundo.setLayout(null);
        imgFundo.setSize(1024, 768);

        //Adiciona a imagem de fundo à tela
        painelPrincipal.add(imgFundo);

        //Exibe o avatar
        imgAvatar = new PainelImagem(imagemAvatar.getImage());
        imgAvatar.setLocation(700, 500);

        //Adiciona o avatar à imagem de fundo
        imgFundo.add(imgAvatar);

        //Exibe o balão
        imgBalao = new PainelImagem(imagemBalao.getImage());

        imgBalao.setLocation(245, 185);
        imgBalao.setLayout(null);

        //Exibe o texto do balão
        textoBalao = new JTextArea();
        String texto = situacao.getFalaAssistente();

        textoBalao.setText(texto);
        textoBalao.setSize(660, 230);
        textoBalao.setLocation(50, 50);
        textoBalao.setEditable(false);
        textoBalao.setAutoscrolls(true);
        textoBalao.setDragEnabled(false);
        //textoBalao.setEnabled(false);
        textoBalao.setFont(new Font("Serif", Font.ITALIC, 16));
        textoBalao.setLineWrap(true);
        textoBalao.setWrapStyleWord(true);
        textoBalao.setForeground(Color.black);

        //Adiciona o texto ao balão
        imgBalao.add(textoBalao);

        //Adiciona o balao à imagem de fundo
        imgFundo.add(imgBalao);

        painelBotoes = new JPanel();
        GerarSaidas(situacao.getSaidas());
    }

    /**
     * Gerar dinâmicamente os botões da saída
     * @param saidas 
     */
    public void GerarSaidas(ArrayList<Saida> saidas) {

        painelBotoes.setOpaque(false);
        //painelBotoes.setT
        painelBotoes.setSize(500, 100);
        painelBotoes.setLocation(100, 600);

        imgFundo.add(painelBotoes);

        for (Saida s : saidas) {
            btn = new JButton(s.getNome());
            btn.setLocation(0, 0);
            btn.setSize(20, 30);
            btn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    JanelaConfirmacaoSaida jcs = new JanelaConfirmacaoSaida(s.getTextoSaida());
                    jcs.setVisible(true);
                }
            });
            botoesSaidas.add(btn);
            painelBotoes.add(btn);
        }
    }
    
    private void acaoBotaoSaida(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
